### ISSUE TITLE
OpenKeychain: Easy PGP

### ISSUE THREAD

**Issue by VNRARA** [FabianHenneke/WearAuthn#12]
**What went wrong?**
[OpenKeyChain](https://play.google.com/store/apps/details?id=org.sufficientlysecure.keychain&hl=nl) doesn't accept the NFC key from WearAuthn: **Error: Initialization failed!** My first question is: Should it be able to tho? It doesn't seem locked to a specific brand security token.

**Steps to reproduce**
1. Inside [OpenKeyChain](https://play.google.com/store/apps/details?id=org.sufficientlysecure.keychain&hl=nl) go to _Use security token_ (if the app has a key setup, use the ⋮ (three dot) symbol and select _"manage my keys"_)
2. Tap the Watch to the back of the phone as explained. 
3. Receive error

**Which model is your watch?**
TicWatch Pro (OG) WF12096

**Which Android version is running on your watch?**

2.19 (H)

**Which version of WearAuthn are you using?**

0.9.16

**Screenshots**
n.a.

**Comment by FabianHenneke** [comment]
In the context of OpenKeychain, a "security token" is an OpenPGP hardware token with NFC support. WearAuthn is an implementation of FIDO2, which is an entirely different standard that is not related to OpenPGP in any way - for example, it can't do any kind of public key encryption.

The confusion probably arises because many popular hardware tokens (such as Yubikeys) support both FIDO2 and OpenPGP.
