### ISSUE TITLE
support BLE

### ISSUE THREAD

**Issue by thedreamwork** [FabianHenneke/WearAuthn#8]
It seems BLE protocol with fido-ctap2 works well. This is [demo](https://www.youtube.com/watch?v=891JhBzr8T4).  Therefore,  I think it is possible WearAuthn offer its authentication capabilities via Bluetooth Low Energy (BLE).

**Comment by FabianHenneke** [comment]
Unfortunately, Android (and thus Wear OS) prevents third-party apps from offering BLE authenticator capabilities: https://github.com/Trojan295/android-webauthn-token/issues/4#issuecomment-594492816

The required permission even can't be granted via adb and thus there is no workaround short of rooting the watch. Since BLE is being deprecated on desktops and both Android and iOS now support NFC as a FIDO transport, there is also no real point to lobby for a change to Android in this regard.
